enum RequestTypes {

  REGISTER = 'REGISTER',
  REGISTERED = 'REGISTERED',
  REGISTER_PLAYER = 'REGISTER_PLAYER',
  GAME_START = 'GAME_START',
  GAME_STARTED = 'GAME_STARTED',
  GET_UPDATE = 'GET_UPDATE',
  UPDATE = 'UPDATE',
  DO_PLAYER_UPDATE = 'DO_PLAYER_UPDATE',
  GET_PLAYER_UPDATE = 'GET_PLAYER_UPDATE',
  UNREGISTER = 'UNREGISTER',
  UNREGISTERED = 'UNREGISTERED',
  GAME_ENDED = 'GAME_ENDED',
  GAME_CLOSED = 'GAME_CLOSED',
  ERROR = 'ERROR'

}

export default RequestTypes;
