enum RequestTypes {

  REGISTER = 'REGISTER',
  UNREGISTER = 'UNREGISTER',
  REGISTER_PLAYER = 'REGISTER_PLAYER',
  DO_PLAYER_UPDATE = 'DO_PLAYER_UPDATE',
  GET_UPDATE = 'GET_UPDATE',
  GAME_START = 'GAME_START',

  REGISTERED = 'REGISTERED',
  NEW_PLAYER_REGISTERED = 'NEW_PLAYER_REGISTERED',
  GAME_STARTED = 'GAME_STARTED',
  GAME_ENDED = 'GAME_ENDED',
  GAME_CLOSED = 'GAME_CLOSED',
  UPDATE = 'UPDATE',
  ERROR = 'ERROR'

}

export default RequestTypes;
