enum RequestTypes {

  REGISTER = 'REGISTER',
  REGISTERED = 'REGISTERED',
  ROUND_START = 'ROUND_START',
  ROUND_STARTED = 'ROUND_STARTED',
  GET_UPDATE = 'GET_UPDATE',
  UPDATE = 'UPDATE',
  DO_PLAYER_UPDATE = 'DO_PLAYER_UPDATE',
  GET_PLAYER_UPDATE = 'GET_PLAYER_UPDATE',
  PLAYER_BOARD = 'PLAYER_BOARD',
  ROUND_ENDED = 'ROUND_ENDED',
  UNREGISTER = 'UNREGISTER',
  UNREGISTERED = 'UNREGISTERED',
  GAME_ENDED = 'GAME_ENDED',
  ERROR = 'ERROR'

}

export default RequestTypes;
